version: 2

jobs:
  test:
    docker:
      - image: clojure:lein-2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-jars-v2-{{ checksum "project.clj" }}
            - clj-jars-v2-
      - run:
          name: Download dependencies
          command: lein deps
      - run:
          name: Run the tests
          command: lein trampoline test
      - run:
          name: Code Coverage
          command: lein trampoline cloverage --codecov
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
          when: always
      - save_cache:
          key: clj-jars-v2-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - store_artifacts:
          path: target/coverage

workflows:
  version: 2
  test:
    jobs:
      - test
