version: 2

jobs:
  lint-kondo-and-eastwood:
    docker:
      - image: cljkondo/clj-kondo:2021.02.13
    steps:
      - checkout
      - run: clj-kondo --lint .
      - run: lein eastwood

  test:
    docker:
      - image: clojure:lein-2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-jars-v2-{{ checksum "project.clj" }}
            - clj-jars-v2-
      - run:
          name: Download dependencies
          command: lein deps
      - run:
          name: Run the tests
          command: lein trampoline test
      - run:
          name: Code Coverage
          command: lein trampoline cloverage --codecov
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
          when: always
      - save_cache:
          key: clj-jars-v2-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - store_artifacts:
          path: target/coverage
  publish:
    docker:
      - image: clojure:lein-2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-jars-v2-{{ checksum "project.clj" }}
            - clj-jars-v2-
      - run:
          name: Download dependencies
          command: lein deps
      - run:
          name: Publish to clojars
          command: lein deploy

workflows:
  version: 2
  test-and-publish:
    jobs:
      - lint-kondo-and-eastwood
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: clojars-publish
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
